config/routes.rb
Rails.application.routes.draw do
  post '/rate', controller: :rater, action: :create, as: 'rate'
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    resources :articles, shallow: true
    get 'profile', controller: :profile, action: :index
  end
  root controller: :home, action: :index
  resources :tags, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, :body, :user_id, presence: true

  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  ratyrate_rateable "rating"
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  attr_accessor :email_confirmation

  geocoded_by :full_address
  after_validation :geocode

  ratyrate_rater

  validates :name,  presence: true,
                    uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20] #Devise is making up a password for a user registering with FB
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  private
  def full_address
    [g_street, g_street2, g_city, g_postcode, g_country].compact.join(', ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  #These methods overwrite Devise methods for where to send users after the method.
  # See more here: https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb

  def configure_permitted_parameters
  #   if params[:user][:email] == params[:user][:email_confirmation]
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  #   else
  #     flash[:error] = "Email confirmation doesn't match"
  #     # in the future, this should return to registration page with information previously entered
  #     redirect_to root_path
  #   end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    if current_user
      @article = Article.new(user_id: current_user.id)
    else
      redirect_to new_user_session_path
      flash[:notice] = error_message
    end
  end

  def show
    @article = Article.find(params[:id])
    @tags = @article.tag_list.sort_by!{ |e| e.downcase }
    @last = @tags.last
  end

  def create
    if current_user
      @article = current_user.articles.create(article_params)
      redirect_to article_path(@article)
    else
      flash[:alert] = error_message
      redirect_to new_user_session_path
    end
  end

  def edit
    if current_user
      @article = Article.find_by_id(params[:id])
    else
      flash[:alert] = error_message
      redirect_to new_user_session_path
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path
    else
      flash[:alert] = edit_error_message
      render :edit
    end
  end

  def index
    @article = Article.find_by(user_id: params[:user_id])
    @user = User.find_by(id: params[:user_id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :user_id, :tag_list)
  end
  def error_message
    "You are not logged in - you need to be logged in to see the page you were trying to reach"
  end
  def edit_error_message
    "Article not saved"
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in kr
    @amount = 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'sek'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @poptags = ActsAsTaggableOn::Tag.most_used(10)
    @last = @poptags.last
    @toprated = get_top_rated_articles
  end

  private
  def get_top_rated_articles
    ratings = []
    articles = Article.all
    articles.each do |hash|
      if hash.id != nil && hash.rating_average != nil
        ratings << {id: hash.id, avg: hash.rating_average[:avg]}
      end
    end
    rating_hash = ratings.sort_by { |hash| hash[:avg]}.reverse
    rated_articles = []
    rating_hash.each do |hash|
      rated_articles << Article.find_by(id: hash[:id])
    end
    rated_articles
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = User.find_by_id(params[:user_id])
    @user_garden_website = url_with_protocol(@user.garden_website)
    @display_garden_website = url_no_protocol(@user.garden_website)
    @map_hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  def stripe
  end

  private
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end

  def url_no_protocol(url)
    /^http/i.match(url) ? url.sub(/^https?\:\/\//, '') : url
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def after_sign_in_path_for(resource)
    user_profile_path(current_user)
  end

  def after_update_path_for(resource)
    user_profile_path(current_user)
  end

  private

  def account_update_params
    params.require(:user).permit(:pro, :name, :email, :password, :password_confirmation, :current_password, :garden_website, :blurb, :g_street, :g_street2, :g_city, :g_postcode, :g_country)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @articles = Article.tagged_with(params[:id])
    @tag = params[:id]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def get
  #   facebook
  # end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_path
    end
  end

  def failure
    flash[:error] = "Facebook login failed"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level.to_sym
      when :notice then 'alert alert-success'
      when :alert then 'alert alert-danger'
    end
  end
end

app/views/articles/edit.html.erb
<h1 class="content-head is-center">Update article</h1>
<%= form_for @article, url:{action: "update"}, html: { class: 'pure-form pure-form-aligned' } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pure-control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="pure-control-group">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="pure-control-group">
    <%= f.label :tag_list, 'Tags' %>
    <%= f.text_field :tag_list, placeholder: "Tags separated with comma" %>
  </div>
  <p>
    <%= f.submit 'Update article', class: 'hundra pure-button pure-button-primary'  %>
  </p>

<% end %>

app/views/articles/index.html.erb
<h1 class="content-head is-center"> Articles </h1>
<% @user.articles.each do |article| %>
  <ul>
    <li><%= link_to article.title, article %>

  </ul>
<% end %>

app/views/articles/new.html.erb
<h1 class="content-head is-center">Publish article</h1>
<%= form_for @article, url:{action: "create"}, html: { class: 'pure-form pure-form-aligned' } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pure-control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="pure-control-group">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="pure-control-group">
    <%= f.label :tag_list, 'Tags' %>
    <%= f.text_field :tag_list, placeholder: "Tags separated with comma" %>
  </div>
  <p>
    <%= f.submit 'Publish article', class: 'hundra pure-button pure-button-primary'  %>
  </p>

<% end %>

app/views/articles/show.html.erb
<%= javascript_include_tag 'ratyrate' %>

<h1 class="content-head is-center"> <%= @article.title %></h1>
<p>
  <%= @article.body %>
</p>
<p>
  Author: <%= link_to @article.user.name, user_profile_path(@article.user) %>
</p>
<p>
  <% unless @tags.first.nil? %>Tags:<% end %>
  <% @tags.each do |tag| %>
    <%= link_to tag, tag_path(tag) %><% unless tag == @last || @tags.nil? %>,<% end %>
  <% end %>
</p>
<% if current_user == @article.user%>
  <%= link_to 'Edit article', edit_article_path %>
<% end %>
<div>
<% if current_user && current_user != @article.user %>
  <p>
    Rate this article: <%= rating_for_user @article, current_user, 'rating',
      disable_after_rate: false,
      cancel: false,
      space: true %><br>
  </p>
<% end %>
<% unless @article.rating_average.nil? %>
  Average rating: <%= rating_for @article, 'rating' %>
<% end %>
</div>

app/views/charges/new.html.erb
<%= stripe_javascript_tag %>

Sign up for pro membership

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: 100 kr</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="10000"
          data-currency="sek"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<div class="startheader">
</div>

<% if current_user %>
  <h1 class="content-head is-center">Welcome, <%= current_user[:name] %></h1>
<% else %>
  <h1 class="content-head is-center">Home#index</h1>
<% end %>

<div>
  <p>
    Popular tags:
    <% @poptags.each do |hash| %>
      <%= link_to hash.name, tag_path(hash.name) %>
      <% unless hash == @poptags.last || @poptags.nil?%>, <% end %>
    <% end %>
  </p>
</div>

<div>
    <h1 class="content-head is-center">Top rated articles:</h1>
    <ul>
      <% @toprated.each do |hash| %>
        <li><%= link_to hash.title, hash %>
      <% end %>
    </ul>
</div>

<h1 class="content-head is-center">Current Articles</h1>
<% if Article.all != [] %>
  <% Article.all.reverse.first(10).each do |article| %>
  <ul>
    <li><%= link_to article.title, article %></li>
  </ul>
  <% end %>

<% else %>
  <p> No articles written </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenClub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'pure-min' %>
    <%= stylesheet_link_tag    'grids-responsive-min' %>
    <%= stylesheet_link_tag    'alerts' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <div class="menu pure-menu pure-menu-horizontal">
        <%= link_to 'GARDEN CLUB', root_path, class: 'pure-menu-heading pure-menu-link'%>
        <ul class="pure-menu-list">
          <% if current_user %>
            <li class="pure-menu-item"><%= link_to 'My Profile', user_profile_path(current_user), class: 'pure-menu-link' %></li>
            <li class="pure-menu-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'pure-menu-link' %></li>
          <% else %>
            <li class="pure-menu-item"><%= link_to 'Log In', new_user_session_path, class: 'pure-menu-link' %></li>
          <% end %>
          <% if user_signed_in? %>
            <li class="pure-menu-item"><%= link_to 'Write article', new_user_article_path(current_user), class: 'pure-menu-link' %></a></li>
          <% end %>
        </ul>
    </div>

    <div class="pure-g">
      <div class="pure-u-1">
        <% flash.each do |key, value| %>
        <div class="is-center <%= flash_class(key) %>">
            <%= value %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tags/show.html.erb
<h1 class="content-head is-center"> Articles tagged with <%= @tag %></h1>
<ul>
  <% @articles.each do |hash| %>
    <li><%= link_to hash.title, article_path(hash.id) %></li>
  <% end %>
</ul>